// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbsbmots0YPjOCNMZ4T7DTCdmjKMz-fjE',
    appId: '1:203894246575:web:2091894db5faccefbe985a',
    messagingSenderId: '203894246575',
    projectId: 'triptales-4a732',
    authDomain: 'triptales-4a732.firebaseapp.com',
    storageBucket: 'triptales-4a732.appspot.com',
    measurementId: 'G-FPXWR9PRB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyMwzkrdp1gq8Y-Zi4HvqB7D_ZahDcqDk',
    appId: '1:203894246575:android:1f7c741e9f4f96b2be985a',
    messagingSenderId: '203894246575',
    projectId: 'triptales-4a732',
    storageBucket: 'triptales-4a732.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4EVixKDkLzB5MI-YSxAx4OgveC1b-vBY',
    appId: '1:203894246575:ios:404e48ea1c644cb8be985a',
    messagingSenderId: '203894246575',
    projectId: 'triptales-4a732',
    storageBucket: 'triptales-4a732.appspot.com',
    iosBundleId: 'com.example.tripTales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4EVixKDkLzB5MI-YSxAx4OgveC1b-vBY',
    appId: '1:203894246575:ios:2fed041919dc69fcbe985a',
    messagingSenderId: '203894246575',
    projectId: 'triptales-4a732',
    storageBucket: 'triptales-4a732.appspot.com',
    iosBundleId: 'com.example.tripTales.RunnerTests',
  );
}
